### ISSUE TITLE
Add a custom logo

### ISSUE THREAD

**Issue by Romaixn** [Romaixn/quizz-hop#48]
It would be cool to have a custom logo, very simple, minimal

**Comment by KaranSinghBisht** [comment]
Hey @Romaixn, I would like to take up this issue.

**Comment by Romaixn** [comment]
Thank you for your contribution! I have assigned you

**Comment by KaranSinghBisht** [comment]
Hey @Romaixn, Here is what I came up with, hope you like it!
 
![image](https://user-images.githubusercontent.com/69008866/137100468-04b978a1-8673-46b7-8152-0599d78d04b1.png)

**Comment by Romaixn** [comment]
Really amazing @KaranSinghBisht ! Could you send them to me in svg?

**Comment by KaranSinghBisht** [comment]
Sure @Romaixn, all three?

**Comment by Romaixn** [comment]
Yes please :)

**Comment by Romaixn** [comment]
Thank you very much! Happy Hacktoberfest ;)

**Comment by KaranSinghBisht** [comment]
@Romaixn can you kindly put the label on the pull request and accept it? Issues don't count.
